/**
 * @module shared/snip-filters
 * Materializes Harns-bundled Snip filters to a real filesystem path.
 */

import { dirname, fromFileUrl, join } from "@std/path";
import { HOME_DIR } from "../constants.js";

const __dirname = dirname(fromFileUrl(import.meta.url));
const BUNDLED_SNIP_FILTERS_DIR = join(__dirname, "..", "snip-filters");
const FILTER_FILE_NAMES = ["deno-fmt.yaml", "deno-lint.yaml", "deno-test.yaml"];

/**
 * @param {string} value
 * @returns {string}
 */
function tomlString(value) {
    return JSON.stringify(value);
}

/**
 * @param {string} path
 * @param {string} content
 * @returns {Promise<boolean>} true when a write happened
 */
async function writeIfChanged(path, content) {
    try {
        if (await Deno.readTextFile(path) === content) return false;
    } catch (error) {
        if (!(error instanceof Deno.errors.NotFound)) throw error;
    }
    await Deno.writeTextFile(path, content);
    return true;
}

/**
 * @param {string} content
 * @returns {Promise<string>}
 */
async function sha256Hex(content) {
    const data = new TextEncoder().encode(content);
    const hash = await crypto.subtle.digest("SHA-256", data);
    return [...new Uint8Array(hash)].map((byte) => byte.toString(16).padStart(2, "0")).join("");
}

/**
 * @param {string} path
 * @returns {Promise<Record<string, string>>}
 */
async function readTrustStore(path) {
    try {
        const parsed = JSON.parse(await Deno.readTextFile(path));
        if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
            return /** @type {Record<string, string>} */ (parsed);
        }
    } catch (error) {
        if (!(error instanceof Deno.errors.NotFound)) throw error;
    }
    return {};
}

/**
 * @param {{ homeDir?: string, bundledDir?: string }} [options]
 * @returns {{ snipRoot: string, filtersDir: string, configPath: string, userFiltersDir: string, trustStorePath: string }}
 */
export function getHarnsSnipPaths(options = {}) {
    const homeDir = options.homeDir || HOME_DIR || Deno.env.get("HOME") || Deno.cwd();
    const snipRoot = join(homeDir, ".hns", "snip");
    return {
        snipRoot,
        filtersDir: join(snipRoot, "filters"),
        configPath: join(snipRoot, "config.toml"),
        userFiltersDir: join(homeDir, ".config", "snip", "filters"),
        trustStorePath: join(homeDir, ".config", "snip", "trusted.json"),
    };
}

/**
 * @param {{ homeDir?: string, bundledDir?: string }} [options]
 * @returns {Promise<{ configPath: string, filtersDir: string, written: string[] }>}
 */
export async function ensureHarnsSnipFilters(options = {}) {
    const bundledDir = options.bundledDir || BUNDLED_SNIP_FILTERS_DIR;
    const paths = getHarnsSnipPaths(options);
    const written = [];

    await Deno.mkdir(paths.filtersDir, { recursive: true });

    /** @type {Array<{ path: string, content: string }>} */
    const materializedFilters = [];
    for (const fileName of FILTER_FILE_NAMES) {
        const sourcePath = join(bundledDir, fileName);
        const targetPath = join(paths.filtersDir, fileName);
        const content = await Deno.readTextFile(sourcePath);
        if (await writeIfChanged(targetPath, content)) written.push(targetPath);
        materializedFilters.push({ path: targetPath, content });
    }

    await Deno.mkdir(dirname(paths.trustStorePath), { recursive: true });
    const trustStore = await readTrustStore(paths.trustStorePath);
    let trustChanged = false;
    for (const filter of materializedFilters) {
        const hash = await sha256Hex(filter.content);
        if (trustStore[filter.path] !== hash) {
            trustStore[filter.path] = hash;
            trustChanged = true;
        }
    }
    if (trustChanged) {
        const trustJson = JSON.stringify(trustStore, null, 2) + "\n";
        if (await writeIfChanged(paths.trustStorePath, trustJson)) written.push(paths.trustStorePath);
    }

    await Deno.mkdir(dirname(paths.configPath), { recursive: true });

    const config = [
        "# Generated by Harns. Do not edit; Harns may overwrite this file.",
        "",
        "[filters]",
        `dir = [${tomlString(paths.userFiltersDir)}, ${tomlString(paths.filtersDir)}]`,
        "",
    ].join("\n");

    if (await writeIfChanged(paths.configPath, config)) written.push(paths.configPath);

    return { configPath: paths.configPath, filtersDir: paths.filtersDir, written };
}
