/**
 * @module shared/version
 *
 * Generated by scripts/write-version.js. The build pipeline overwrites
 * this file with the current git short hash before `deno compile`.
 */

export const HNS_VERSION = "e9ebfb5";
