/**
 * @module scripts/write-version
 *
 * Build-time helper: writes the current git short hash into
 * `src/shared/version.js` so the compiled binary reports its build hash.
 * Run before `deno compile`. Falls back to "dev" if git is unavailable
 * or the working tree is not a repo.
 */

const FILE_PATH = "src/shared/version.js";

let hash = "dev";
try {
    const cmd = new Deno.Command("git", { args: ["rev-parse", "--short", "HEAD"] });
    const { success, stdout } = cmd.outputSync();
    if (success) {
        hash = new TextDecoder().decode(stdout).trim() || "dev";
    }
} catch (_e) {
    hash = "dev";
}

const content = `/**
 * @module shared/version
 *
 * Generated by scripts/write-version.js. The build pipeline overwrites
 * this file with the current git short hash before \`deno compile\`.
 */

export const HNS_VERSION = ${JSON.stringify(hash)};
`;

await Deno.writeTextFile(FILE_PATH, content);
console.log(`[hns] wrote ${FILE_PATH} with version ${hash}`);
