/**
 * @module scripts/write-version
 *
 * Build-time helper: writes the current release tag or git short hash into
 * `src/shared/version.js` so the compiled binary reports its build version.
 * Run before `deno compile`. Falls back to "dev" if git is unavailable
 * or the working tree is not a repo.
 */

const FILE_PATH = "src/shared/version.js";

/**
 * @typedef {(name: string) => string | undefined} EnvReader
 */

/**
 * @typedef {(args: string[]) => string | undefined} GitRunner
 */

/**
 * Read an environment variable, returning undefined when env access is not
 * allowed. This keeps non-release build paths on the existing git fallback.
 *
 * @param {string} name
 * @returns {string | undefined}
 */
function readEnvValue(name) {
    try {
        return Deno.env.get(name);
    } catch (_e) {
        return undefined;
    }
}

/**
 * @param {string[]} args
 * @returns {string | undefined}
 */
function runGitCommand(args) {
    try {
        const cmd = new Deno.Command("git", { args, stdout: "piped", stderr: "null" });
        const { success, stdout } = cmd.outputSync();
        if (!success) return undefined;
        return new TextDecoder().decode(stdout).trim() || undefined;
    } catch (_e) {
        return undefined;
    }
}

/**
 * @param {EnvReader} [readEnv]
 * @returns {string | undefined}
 */
export function getGitHubTagName(readEnv = readEnvValue) {
    const refName = readEnv("GITHUB_REF_NAME");
    if (readEnv("GITHUB_REF_TYPE") === "tag" && refName) return refName;

    const ref = readEnv("GITHUB_REF");
    if (ref?.startsWith("refs/tags/")) return ref.slice("refs/tags/".length) || undefined;

    return undefined;
}

/**
 * @param {GitRunner} [runGit]
 * @returns {string | undefined}
 */
export function getExactGitTag(runGit = runGitCommand) {
    return runGit(["describe", "--tags", "--exact-match", "HEAD"]);
}

/**
 * @param {GitRunner} [runGit]
 * @returns {string | undefined}
 */
export function getGitShortHash(runGit = runGitCommand) {
    const gitShortHash = runGit(["rev-parse", "--short", "HEAD"]);

    return gitShortHash || undefined;
}

/**
 * @param {{ readEnv?: EnvReader, runGit?: GitRunner }} [options]
 * @returns {string}
 */
export function resolveBuildVersion(options = {}) {
    const readEnv = options.readEnv ?? readEnvValue;
    const runGit = options.runGit ?? runGitCommand;

    return getGitHubTagName(readEnv) ?? getExactGitTag(runGit) ?? getGitShortHash(runGit) ?? "dev";
}

/**
 * @param {string} filePath
 * @param {string} version
 * @returns {Promise<void>}
 */
export async function writeVersionFile(filePath = FILE_PATH, version = resolveBuildVersion()) {
    const content = `/**
 * @module shared/version
 *
 * Generated by scripts/write-version.js. The build pipeline overwrites
 * this file with the current build version before \`deno compile\`.
 */

export const VERSION = ${JSON.stringify(version)};
`;

    await Deno.writeTextFile(filePath, content);
    console.log(`[wld] wrote ${filePath} with version ${version}`);
}

if (import.meta.main) {
    await writeVersionFile();
}
