/**
 * @module tools/switch-agent
 * Tool an agent uses to hand off the conversation to another agent.
 *
 * Behavior:
 *   1. The tool result terminates the calling agent's turn immediately
 *      (`terminate: true`) so no more text is generated by the previous agent.
 *   2. It queues a root swap to the target agent and records a `pendingSwitchHandoff`
 *      containing the `reason` argument.
 *   3. The chat-session loop then applies the swap (rebuilding the root for the
 *      new agent) and re-enters the turn with `reason` as the first user
 *      message to the new agent — so the conversation continues seamlessly.
 *
 * Because of (1), the `reason` argument is not just a justification — it IS the
 * first message the new agent sees. The tool/parameter descriptions are written
 * to push the LLM toward crafting a useful, self-contained handoff prompt.
 */

import { Type } from "@earendil-works/pi-ai";
import { defineTool } from "@earendil-works/pi-coding-agent";
import { AGENTS } from "../constants.js";
import { getActiveUiAPI, setActiveAgent } from "../shared/interactive/chat-session.js";
import { createDirectAgentHandler } from "../shared/session/direct-agent.js";
import { listAvailableAgents } from "../shared/session/agents.js";
import { setPendingSwitchHandoff } from "../shared/session/session-state.js";

/**
 * Core logic for switching the active agent.
 *
 * @param {Object} params
 * @param {string} params.agentName
 * @param {string} params.reason
 * @param {import('../shared/workflow/workflow.js').UiAPI | null | undefined} uiAPI
 * @returns {Promise<import('@earendil-works/pi-coding-agent').AgentToolResult<{ agentName: string, reason: string } | null>>}
 */
export async function executeSwitchAgent(params, uiAPI) {
    const { agentName, reason } = params;

    if (!uiAPI) {
        return {
            content: [{
                type: "text",
                text:
                    "Error: This tool requires an active UI session to perform the switch. Please ensure you're running in interactive mode.",
            }],
            details: null,
        };
    }

    const target = agentName.toLowerCase().trim();

    const agents = await listAvailableAgents();
    const match = agents.find((agent) => agent.name === target);

    if (!match) {
        return {
            content: [{
                type: "text",
                text: `Error: Unknown agent "${agentName}". Available agents: ${
                    agents.map((agent) => agent.name).join(", ")
                }`,
            }],
            details: null,
        };
    }

    const handler = createDirectAgentHandler(target);
    setActiveAgent(match.name, handler, uiAPI, match.model);
    setPendingSwitchHandoff({ agentName: match.name, reason });

    uiAPI.appendSystemMessage(`Agent hand-off: Switching to ${match.displayName}. Reason: ${reason}`);

    return {
        content: [],
        details: { agentName: match.name, reason },
        // Halt the current agent's generation — the new agent picks up from here.
        terminate: true,
    };
}

/**
 * Tool for switching the active agent in the interactive session.
 */
export const switchAgentTool = defineTool({
    name: "switch_agent",
    label: "Switch Agent",
    description: `Hand off the conversation to another agent (e.g. '${AGENTS.PLANNER}', '${AGENTS.ARCHITECT}', ` +
        `'${AGENTS.OPERATOR}', '${AGENTS.ROUTER}') when the user's request is better served by a ` +
        `different role. Calling this tool ENDS your turn immediately — you will not generate any ` +
        `more text after the call. The 'reason' argument is delivered to the new agent as its first ` +
        `user message, so write it as a self-contained prompt that lets the new agent continue the ` +
        `conversation without seeing your prior turn.`,
    parameters: Type.Object({
        agentName: Type.String({
            description: `Identifier of the agent to hand off to (e.g. '${AGENTS.PLANNER}', ` +
                `'${AGENTS.ARCHITECT}', '${AGENTS.OPERATOR}', '${AGENTS.ROUTER}'). Must match an ` +
                `agent definition filename.`,
        }),
        reason: Type.String({
            description: "The first user message the new agent will receive. Restate the user's ask in " +
                "your own words and include any context the new agent needs to act on it — they " +
                "do not see your prior reasoning. Address the new agent in the second person " +
                "(e.g. 'The user wants you to …'). Do NOT write a justification for the switch.",
        }),
    }),
    execute(_toolCallId, params, _signal, _onUpdate, _context) {
        return executeSwitchAgent(
            /** @type {{ agentName: string, reason: string }} */ (params),
            getActiveUiAPI(),
        );
    },
});
